name: Scanning the code

on:
  workflow_call:

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'

    - name: Upload trivy scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-results
        path: trivy-results.txt
