name: Building Infrastructure with Terraform

on:
  workflow_call:


jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      secret_name: ${{ steps.tf_output.outputs.secret_name }}

    steps:

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Configure AWS ( OIDC )
      uses: aws-actions/configure-aws-credentials@v6.0.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-south-1

    - name: Setting Up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply --auto-approve tfplan

    - name: Get Secret Name
      id: tf_output
      working-directory: ./terraform
      run: |
        SECRET_NAME=$(terraform output -raw secrets_manager_secret_name)
        echo "secret_name=$SECRET_NAME" >> $GITHUB_OUTPUT
        echo "Secret name: $SECRET_NAME"
